version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: phumbe/airplaces:latest
    environment:
      - PYTHONUNBUFFERED=0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
